[workspace]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "jarlang-mojo"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
mojo = ">=0.25.7.0.dev2025100215,<0.26"
